name: Minecraft_Kingdom_War
version: '${project.version}'
main: org.jandy.minecraft_kingdom_war.Minecraft_Kingdom_War
api-version: '1.20'
database: sqlite
author: jandy
commands:
  kw:
    #描述这个命令
    description: 测试命令
    #用法
    usage: /<command>
    #执行此命令的人所需的权限
    permission: kw.command
    #没有权限的提示消息
    permission-message: 你不能执行它.